#DATASOURCE_INSTANCE_HOSTNAME: localhost
#DATASOURCE_INSTANCE_PORT: 5432
DATASOURCE_INSTANCE_HOSTNAME: 10.60.150.56
DATASOURCE_INSTANCE_PORT: 32070

server:
  port: 8050
  contextPath:

#logging:
#  level: DEBUG

telegram:
  bot:
    enabled: false
    name: bvn13_blog_test_bot
    channel: bvn13_blog_test
    token_file: private/telegram_bot_test.token
    master_name: bvn13


spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  jade4j:
    caching: false

  dataSource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_INSTANCE_HOSTNAME}:${DATASOURCE_INSTANCE_PORT}/blog
    username: blog
    password: blogpass

  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hbm2ddl.auto: update
    show_sql: true
    use_sql_comments: true
    format_sql: true

  redis:
    host: localhost
    port: 6379
    default_expire_time: 86400


  session:
    store-type: redis

  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

