#DATASOURCE_INSTANCE_HOSTNAME: localhost
#DATASOURCE_INSTANCE_PORT: 5432
DATASOURCE_INSTANCE_HOSTNAME: 10.60.150.56
DATASOURCE_INSTANCE_PORT: 32070

server:
  port: 8051
#  contextPath:

telegram:
  bot:
    enabled: false
    name: bvn13_blog_test_bot
    channel: bvn13_blog_test
    token_file: private/telegram_bot_test.token
    master_name : bvn13

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true   #表示将自己的ip注册到eureka上，如果不配置该属性或者设置为false，则表示注册微服务所在的操作系统的hostname到eureka上
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 600000
#        readTimeout: 600000
#  hystrix:
#    enabled: false

spring:
  application:
    name: springblog-microservice1

  jackson:
    deserialization: true
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    generator: true

  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true

  profiles:
    active: dev

  thymeleaf:
    cache: false

#  jade4j:
#    caching: false
#  main:
#    web-environment: false  # 禁用 web
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration

  dataSource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_INSTANCE_HOSTNAME}:${DATASOURCE_INSTANCE_PORT}/blog
    username: blog
    password: blogpass

  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    ## create 为每次启动时都初始化
    ## update 为每次启动时不初始化
    hbm2ddl.auto: update
    show_sql: true
    use_sql_comments: true
    format_sql: true

  redis:
    host: localhost
    port: 6379
    default_expire_time: 86400


  session:
    store-type: redis

  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb


security:
  basic:
    enabled: false
